# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
branches:
  ignore:
    - master
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: kpachar/san-docker-images:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    branches:
      only:
        - build
        - release

    steps:
      - checkout
      
      - restore_cache:
          key: jars-{{ checksum "praatah/android/build.gradle" }}-{{ checksum  "praatah/android/app/build.gradle" }}

      - run: cd praatah/android && ./gradlew assembleRelease

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "praatah/android/build.gradle" }}-{{ checksum  "praatah/android/app/build.gradle" }}

      # run tests!
      - run: yarn test



